MESSAGE( "Installing GUI" )

SET( CMAKE_COMMAND      "@CMAKE_COMMAND@" )
SET( CMAKE_BUILD_TYPE   "@CMAKE_BUILD_TYPE@" )
SET( CMAKE_CXX_COMPILER "@CMAKE_CXX_COMPILER@" )
SET( CMAKE_CXX_FLAGS    "@CMAKE_CXX_FLAGS@" )
SET( CXX_STD            "@CXX_STD@" )
SET( TIMER_INSTALL_DIR  "@TIMER_INSTALL_DIR@" )
SET( QT_VERSION         "@QT_VERSION@" )
SET( QWT_INSTALL_DIR    "@QWT_INSTALL_DIR@" )
SET( TIMER_GUI_SOURCE_DIR "@TIMER_GUI_SOURCE_DIR@" )
SET( TIMER_GUI_INSTALL_DIR "@TIMER_GUI_INSTALL_DIR@" )
SET( TIMER_GUI_BUILD_DIR "@TIMER_GUI_BUILD_DIR@" )

# Configure
EXECUTE_PROCESS( COMMAND ${CMAKE_COMMAND} -DCMAKE_BUILD_TYPE=${CMAKE_BUILD_TYPE} -DCMAKE_CXX_COMPILER=${CMAKE_CXX_COMPILER} -DCMAKE_CXX_FLAGS=${CMAKE_CXX_FLAGS} -DCXX_STD=${CXX_STD} -DTIMER_INSTALL_DIR=${TIMER_INSTALL_DIR} -DQT_VERSION=${QT_VERSION} -DQWT_INSTALL_DIR=${QWT_INSTALL_DIR} -DTIMER_GUI_INSTALL_DIR=${GUI_INSTALL_DIR} ${TIMER_GUI_SOURCE_DIR} WORKING_DIRECTORY ${TIMER_GUI_BUILD_DIR} )

# Build
EXECUTE_PROCESS( COMMAND make install -j ${PROCS_INSTALL} WORKING_DIRECTORY ${TIMER_GUI_BUILD_DIR} )


