INCLUDE( CheckCCompilerFlag )
INCLUDE( CheckCXXCompilerFlag )

FUNCTION( CONFIGURE_LINE_COVERAGE )
    SET( COVERAGE_FLAGS )
    SET( COVERAGE_LIBS )
    IF ( ENABLE_GCOV )
        SET( COVERAGE_FLAGS -DUSE_GCOV )
        SET( CMAKE_REQUIRED_FLAGS ${CMAKE_CXX_FLAGS} -fprofile-arcs -ftest-coverage )
        CHECK_CXX_SOURCE_COMPILES( "int main( ) { return 0;}" profile-arcs )
        IF ( profile-arcs )
            SET( COVERAGE_FLAGS "${COVERAGE_FLAGS} -fprofile-arcs -ftest-coverage" )
            SET( COVERAGE_LIBS ${COVERAGE_LIBS} -fprofile-arcs )
        ENDIF()
        SET( CMAKE_REQUIRED_FLAGS "${CMAKE_CXX_FLAGS} ${COVERAGE_FLAGS} -lgcov" )
        CHECK_CXX_SOURCE_COMPILES( "int main( ) { return 0;}" lgcov )
        IF ( lgcov )
            SET( COVERAGE_LIBS -lgcov ${COVERAGE_LIBS} )
        ENDIF()
        MESSAGE( "Enabling coverage:" )
        MESSAGE( "   COVERAGE_FLAGS = ${COVERAGE_FLAGS}" )
        MESSAGE( "   COVERAGE_LIBS = ${COVERAGE_LIBS}" )
        ADD_DEFINITIONS( ${COVERAGE_FLAGS} )
        SET( COVERAGE_FLAGS ${COVERAGE_FLAGS} PARENT_SCOPE )
        SET( COVERAGE_LIBS ${COVERAGE_LIBS} PARENT_SCOPE )
    ENDIF()
ENDFUNCTION()

# Macro to configure MPI
MACRO( CONFIGURE_MPI )
    CHECK_ENABLE_FLAG( USE_MPI 1 )
    MESSAGE( "MPIEXEC = ${MPIEXEC}" )
    IF ( USE_MPI )
        MESSAGE( "Configuring MPI" )
        IF ( MPIEXEC )
            SET( MPIEXEC_EXECUTABLE ${MPIEXEC} )
        ENDIF()
        # Write mpi test
        SET( MPI_TEST_SRC "${CMAKE_CURRENT_BINARY_DIR}/test_mpi.cpp" )
        FILE( WRITE ${MPI_TEST_SRC} "#include <mpi.h>\n" )
        FILE( APPEND ${MPI_TEST_SRC} "int main( int argc, char** argv ) {\n" )
        FILE( APPEND ${MPI_TEST_SRC} "    MPI_Init( &argc,&argv );\n" )
        FILE( APPEND ${MPI_TEST_SRC} "    MPI_Finalize();\n" )
        FILE( APPEND ${MPI_TEST_SRC} "}\n" )
        # Search for MPI
        IF ( NOT MPI_SKIP_SEARCH )
            FIND_PACKAGE( MPI COMPONENTS C CXX )
            IF ( NOT MPI_FOUND )
                MESSAGE( FATAL_ERROR "CMake did not find MPI, if building without MPI set USE_MPI to false ( default is true )" )
            ENDIF()
        ELSE()
            # Test the compile
            FOREACH( tmp C CXX Fortran )
                IF ( CMAKE_${tmp}_COMPILER )
                    SET( TMP_FLAGS -DINCLUDE_DIRECTORIES=${MPI_CXX_INCLUDE_PATH} )
                    TRY_COMPILE( MPI_TEST_${tmp} ${CMAKE_CURRENT_BINARY_DIR} ${MPI_TEST_SRC} CMAKE_FLAGS ${TMP_FLAGS} LINK_OPTIONS ${MPI_CXX_LINK_FLAGS}
                                LINK_LIBRARIES ${MPI_CXX_LIBRARIES} OUTPUT_VARIABLE OUT_TXT )
                    IF ( NOT ${MPI_TEST_${tmp}} )
                        MESSAGE( FATAL_ERROR "Skipping MPI search and default compile fails:\n${OUT_TXT}" )
                    ENDIF()
                    SET( MPI_C_FOUND TRUE )
                    SET( MPI_CXX_FOUND TRUE )
                    SET( MPI_Fortran_FOUND TRUE )
                ENDIF()
            ENDFOREACH()
        ENDIF()
        # Try and set MPI include directories
        ADD_MPI_FLAGS()
        # Set the MPI languages
        SET( MPI_LANG C CXX Fortran )
        FOREACH( tmp ${MPI_LANG} )
            STRING( STRIP "${MPI_${tmp}_COMPILE_FLAGS}" MPI_${tmp}_COMPILE_FLAGS )
            STRING( STRIP "${MPI_${tmp}_LINK_FLAGS}" MPI_${tmp}_LINK_FLAGS )
            STRING( STRIP "${MPI_${tmp}_LIBRARIES}" MPI_${tmp}_LIBRARIES )
            MESSAGE( "   MPI_${tmp}_FOUND = ${MPI_${tmp}_FOUND}" )
            MESSAGE( "   MPI_${tmp}_COMPILER = ${MPI_${tmp}_COMPILER}" )
            MESSAGE( "   MPI_${tmp}_COMPILE_FLAGS = ${MPI_${tmp}_COMPILE_FLAGS}" )
            MESSAGE( "   MPI_${tmp}_INCLUDE_DIRS = ${MPI_${tmp}_INCLUDE_DIRS}" )
            MESSAGE( "   MPI_${tmp}_LINK_FLAGS = ${MPI_${tmp}_LINK_FLAGS}" )
            MESSAGE( "   MPI_${tmp}_LIBRARIES = ${MPI_${tmp}_LIBRARIES}" )
            MESSAGE( "   MPI_${tmp}_HEADER_DIR = ${MPI_${tmp}_HEADER_DIR}" )
        ENDFOREACH()
        MESSAGE( "   MPIEXEC = ${MPIEXEC}" )
        MESSAGE( "   MPIEXEC_NUMPROC_FLAG = ${MPIEXEC_NUMPROC_FLAG}" )
        MESSAGE( "   MPIEXEC_PREFLAGS = ${MPIEXEC_PREFLAGS}" )
        MESSAGE( "   MPIEXEC_POSTFLAGS = ${MPIEXEC_POSTFLAGS}" )
        IF ( NOT MPI_C_FOUND AND NOT MPI_CXX_FOUND AND NOT MPI_Fortran_FOUND )
            MESSAGE( FATAL_ERROR "MPI not found" )
        ENDIF()
        # Perform a final test compilation
        SET( TMP_FLAGS ${MPI_${tmp}_COMPILE_FLAGS} -DINCLUDE_DIRECTORIES=${MPI_CXX_INCLUDE_DIRS} )
        TRY_COMPILE( MPI_TEST ${CMAKE_CURRENT_BINARY_DIR} ${MPI_TEST_SRC} CMAKE_FLAGS ${TMP_FLAGS} -D"LINK_OPTIONS=${MPI_CXX_LINK_FLAGS}" LINK_LIBRARIES ${MPI_CXX_LIBRARIES}
                    OUTPUT_VARIABLE OUT_TXT )
        IF ( NOT MPI_TEST )
            MESSAGE( FATAL_ERROR "Compiling MPI test fails:\n${OUT_TXT}" )
        ENDIF()
    ENDIF()
    IF ( USE_MPI AND NOT MPIEXEC )
        MESSAGE( FATAL_ERROR "Unable to find MPIEXEC, please set it before continuing" )
    ENDIF()
    IF ( USE_MPI )
        ADD_DEFINITIONS( -DUSE_MPI )
        IF ( MPI_CXX_INCLUDE_DIRS )
            INCLUDE_DIRECTORIES( "${MPI_CXX_INCLUDE_DIRS}" )
        ENDIF()
    ENDIF()
ENDMACRO()

# Function to try and add MPI include flags
FUNCTION( ADD_MPI_FLAGS )
    IF ( MPI_CXX_INCLUDE_DIRS )
        RETURN()
    ENDIF()
    SET( MPI_ARGS )
    # Test if we are using cray wrappers
    EXECUTE_PROCESS( COMMAND ${CMAKE_CXX_COMPILER} --cray-print-opts RESULT_VARIABLE flag ERROR_QUIET OUTPUT_VARIABLE out )
    IF ( "${flag}" STREQUAL "0" )
        SEPARATE_ARGUMENTS( MPI_ARGS NATIVE_COMMAND ${out} )
    ENDIF()
    # Test if we can use mpi --show
    EXECUTE_PROCESS( COMMAND ${CMAKE_CXX_COMPILER} --show RESULT_VARIABLE flag ERROR_QUIET OUTPUT_VARIABLE out )
    IF ( "${flag}" STREQUAL "0" )
        SEPARATE_ARGUMENTS( MPI_ARGS NATIVE_COMMAND ${out} )
    ENDIF()
    # Test if we can use mpi -show
    EXECUTE_PROCESS( COMMAND ${CMAKE_CXX_COMPILER} -show RESULT_VARIABLE flag ERROR_QUIET OUTPUT_VARIABLE out )
    IF ( "${flag}" STREQUAL "0" )
        SEPARATE_ARGUMENTS( MPI_ARGS NATIVE_COMMAND ${out} )
    ENDIF()
    IF ( NOT MPI_ARGS )
        RETURN()
    ENDIF()
    # Parse the arguments
    FOREACH( tmp ${MPI_ARGS} )
        IF ( "${tmp}" MATCHES "^-I" )
            STRING( REGEX REPLACE "^-I" "" tmp "${tmp}" )
            SET( MPI_CXX_INCLUDE_DIRS ${MPI_CXX_INCLUDE_DIRS} ${tmp} )
        ELSEIF ( "${tmp}" MATCHES "^-L" )
            SET( MPI_CXX_LINK_FLAGS ${MPI_CXX_LINK_FLAGS} ${tmp} )
        ELSEIF ( "${tmp}" MATCHES "^-l" )
            SET( MPI_CXX_LIBRARIES ${MPI_CXX_LIBRARIES} ${tmp} )
        ENDIF()
    ENDFOREACH()
    SET( MPI_CXX_LINK_FLAGS ${MPI_CXX_LINK_FLAGS} PARENT_SCOPE )
    SET( MPI_CXX_INCLUDE_DIRS ${MPI_CXX_INCLUDE_DIRS} PARENT_SCOPE )
    SET( MPI_CXX_LIBRARIES ${MPI_CXX_LIBRARIES} PARENT_SCOPE )
    IF ( NOT MPI_C_INCLUDE_DIRS )
        SET( MPI_C_LINK_FLAGS ${MPI_CXX_LINK_FLAGS} PARENT_SCOPE )
        SET( MPI_C_INCLUDE_DIRS ${MPI_CXX_INCLUDE_DIRS} PARENT_SCOPE )
        SET( MPI_C_LIBRARIES ${MPI_CXX_LIBRARIES} PARENT_SCOPE )
    ENDIF()
ENDFUNCTION()

# Macro to configure system-specific libraries and flags
MACRO( CONFIGURE_SYSTEM )
    # First check/set the compile mode
    IF ( NOT CMAKE_BUILD_TYPE )
        MESSAGE( FATAL_ERROR "CMAKE_BUILD_TYPE is not set" )
    ENDIF()
    CHECK_ENABLE_FLAG( USE_STATIC 0 )
    CHECK_ENABLE_FLAG( USE_SHARED 0 )
    # Set shared/static library
    IF ( NOT DEFINED LIB_TYPE )
        IF ( ENABLE_SHARED )
            SET( LIB_TYPE SHARED )
        ELSE()
            SET( LIB_TYPE STATIC )
        ENDIF()
    ENDIF()
    # Add system dependent flags
    MESSAGE( "System is: ${CMAKE_SYSTEM_NAME}" )
    IF ( ${CMAKE_SYSTEM_NAME} STREQUAL "Windows" )
        # Windows specific system libraries
    ELSEIF ( ${CMAKE_SYSTEM_NAME} STREQUAL "Linux" )
        # Linux specific system libraries
        SET( SYSTEM_LIBS -lpthread -ldl )
        IF ( CMAKE_Fortran_COMPILER_WORKS )
            IF ( CMAKE_COMPILER_IS_GNUG77 OR ( ${CMAKE_Fortran_COMPILER_ID} MATCHES "GNU" ) )
                SET( SYSTEM_LIBS ${SYSTEM_LIBS} -lgfortran )
            ENDIF()
        ENDIF()
        SET( CMAKE_C_FLAGS " ${CMAKE_C_FLAGS} -fPIC" )
        SET( CMAKE_CXX_FLAGS " ${CMAKE_CXX_FLAGS} -fPIC" )
    ELSEIF ( ${CMAKE_SYSTEM_NAME} STREQUAL "Darwin" )
        # Max specific system libraries
        SET( SYSTEM_LIBS -lpthread -ldl )
    ELSEIF ( ${CMAKE_SYSTEM_NAME} STREQUAL "Generic" )
        # Generic system libraries
    ELSE()
        MESSAGE( FATAL_ERROR "OS not detected" )
    ENDIF()
    # Set the compile flags based on the build
    SET_CXX_STD()
    SET_COMPILER_FLAGS()
    # Add the static flag if necessary
    IF ( USE_STATIC )
        SET_STATIC_FLAGS()
    ENDIF()
    # Print some flags
    MESSAGE( "LDLIBS = ${LDLIBS}" )
    # Configure CUDA/HIP
    CONFIGURE_CUDA()
    CONFIGURE_HIP()
ENDMACRO()

# Macro to add user c++ std
MACRO( SET_CXX_STD )
    # Set the C++ standard
    SET( CMAKE_CXX_EXTENSIONS OFF )
    IF ( NOT CMAKE_CXX_STANDARD )
        IF ( CXX_STD )
            IF ( ${CXX_STD} STREQUAL "NONE" )
                # Do nothing
            ELSEIF ( "${CXX_STD}" MATCHES "^(98|11|14|17)$" )
                MESSAGE( FATAL_ERROR "C++20 or newer required" )
            ELSEIF ( "${CXX_STD}" MATCHES "^(20|23|26)$" )
                SET( CMAKE_CXX_STANDARD ${CXX_STD} )
                SET( CXX_STD_FLAG ${CMAKE_CXX${CXX_STD}_STANDARD_COMPILE_OPTION} )
            ELSE()
                MESSAGE( FATAL_ERROR "Unknown C++ standard ${CXX_STD} ( 98,11,14,17,20,23,26,NONE )" )
            ENDIF()
        ELSE()
            SET( CMAKE_CXX_STANDARD 20 )
            MESSAGE( "C++ standard is not set, default is c++20" )
        ENDIF()
    ENDIF()
    IF ( NOT ( "${CMAKE_CXX_STANDARD}" MATCHES "^(20|23|26)$" ) )
        MESSAGE( FATAL_ERROR "C++20 or newer required" )
    ENDIF()
    # Set the C standard
    IF ( NOT CMAKE_C_STANDARD )
        IF ( C_STD )
            IF ( ${C_STD} STREQUAL "NONE" )
                # Do nothing
            ELSEIF ( "${CXX_STD}" MATCHES "^(90|99|11|17|23)$" )
                SET( CMAKE_C_STANDARD ${C_STD} )
            ELSE()
                MESSAGE( FATAL_ERROR "Unknown C standard ${C_STD} ( 90,99,11,17,23,NONE )" )
            ENDIF()
        ELSE()
            IF ( "${CMAKE_CXX_STANDARD}" MATCHES "^(20)$" )
                SET( CMAKE_C_STANDARD 17 )
            ELSEIF ( "${CMAKE_CXX_STANDARD}" MATCHES "^(23|26)$" )
                SET( CMAKE_C_STANDARD 23 )
            ELSE()
                MESSAGE( FATAL_ERROR "Unknown C++ standard" )
            ENDIF()
        ENDIF()
    ENDIF()
ENDMACRO()

# Macro to configure TimerUtility-specific options
MACRO( CONFIGURE_TIMER )
    SET( CMAKE_INSTALL_RPATH_USE_LINK_PATH TRUE )
    SET( CMAKE_BUILD_WITH_INSTALL_RPATH TRUE )
    SET( CMAKE_INSTALL_RPATH ${CMAKE_INSTALL_RPATH} "${${PROJ}_INSTALL_DIR}/lib" )
    # Set the maximum number of processors for the tests
    IF ( NOT TEST_MAX_PROCS )
        SET( TEST_MAX_PROCS 32 )
    ENDIF()
    # Write the C++ standard we are using
    FILE( WRITE "${${PROJ}_INSTALL_DIR}/include/ProfilerDefinitions.h" "#define TIMER_CXX_STD ${CMAKE_CXX_STANDARD}\n" )
    # Check if we want to enable the traps for new/delete
    CHECK_ENABLE_FLAG( OVERLOAD_NEW 1 )
    IF ( NOT OVERLOAD_NEW OR DISABLE_NEW_OVERLOAD )
        FILE( APPEND "${${PROJ}_INSTALL_DIR}/include/ProfilerDefinitions.h" "#define TIMER_DISABLE_NEW_OVERLOAD\n" )
    ELSE()
        FILE( APPEND "${${PROJ}_INSTALL_DIR}/include/ProfilerDefinitions.h" "#define TIMER_ENABLE_NEW_OVERLOAD\n" )
    ENDIF()
    IF ( USE_CUDA )
        FIND_PACKAGE( CUDAToolkit REQUIRED )
        LIST( GET CUDAToolkit_INCLUDE_DIRS 0 PRIMARY_CUDA_INCLUDE )
        STRING( REPLACE "/targets/x86_64-linux" "" NVTX_INCLUDE "${PRIMARY_CUDA_INCLUDE}" )
        MESSAGE( "CUDAToolkit_INCLUDE_DIRS: ${NVTX_INCLUDE}" )
        MESSAGE( "NVTX_INCLUDE: ${NVTX_INCLUDE}" )
        IF ( NVTX_INCLUDE )
            FILE( APPEND "${${PROJ}_INSTALL_DIR}/include/ProfilerDefinitions.h" "#define TIMER_USE_CUDA\n" )
        ENDIF()
    ENDIF()
    IF ( USE_HIP )
        #FILE( APPEND "${${PROJ}_INSTALL_DIR}/include/ProfilerDefinitions.h" "#define TIMER_USE_HIP\n" )
    ENDIF()
    # Disable CMake warning for unused flags
    NULL_USE( QWT_SRC_DIR )
    NULL_USE( QWT_URL )
ENDMACRO()

# Macro to find QT
MACRO( CONFIGURE_QT )
    IF ( NOT DEFINED QT_VERSION )
        SET( QT_VERSION "5" )
    ENDIF()
    IF ( ${QT_VERSION} EQUAL "4" )
        # Using Qt4
        SET( QT "QT4" )
        SET( Qt "Qt4" )
        SET( QT_COMPONENTS QtCore QtGui QtOpenGL QtSvg QtSql )
        MESSAGE( WARNING "QT4 support is deprecated" )
    ELSEIF ( ${QT_VERSION} EQUAL "5" )
        # Using Qt5
        SET( QT "QT5" )
        SET( Qt "Qt5" )
        SET( QT_COMPONENTS Core Gui OpenGL Svg Sql )
    ELSE()
        MESSAGE( FATAL_ERROR "Unknown Qt version" )
    ENDIF()
    FIND_PACKAGE( ${Qt} COMPONENTS ${QT_COMPONENTS} REQUIRED )
    SET( QT_FOUND ${Qt}_FOUND )
    IF ( NOT ${Qt}_FOUND )
        MESSAGE( "${Qt} not found, disabling" )
        RETURN()
    ENDIF()
    MESSAGE( "${Qt} found" )
    IF ( ${QT_VERSION} EQUAL "5" )
        GET_TARGET_PROPERTY( QT_QMAKE_EXECUTABLE ${Qt}::qmake IMPORTED_LOCATION )
    ENDIF()
ENDMACRO()

# Macro to configure QWT
MACRO( CONFIGURE_QWT )
    IF ( QWT_INSTALL_DIR )
        RETURN()
    ENDIF()
    INCLUDE( ProcessorCount )
    INCLUDE( ExternalProject )
    PROCESSORCOUNT( PROCS_INSTALL )
    SET( QWT_BUILD_DIR "${CMAKE_BINARY_DIR}/QWT-prefix/src/QWT-build" )
    SET( QWT_SRC_DIR "${CMAKE_BINARY_DIR}/QWT-prefix/src/QWT-src" )
    SET( QWT_INSTALL_DIR "${${PROJ}_INSTALL_DIR}/qwt" )
    EXTERNALPROJECT_ADD(
        QWT
        URL "${QWT_URL}"
        SOURCE_DIR "${QWT_SRC_DIR}"
        PATCH_COMMAND cmake -P ${CMAKE_CURRENT_LIST_DIR}/cmake/QWT.patch.cmake
        CONFIGURE_COMMAND ${QT_QMAKE_EXECUTABLE} QWT_INSTALL_PREFIX=${QWT_INSTALL_DIR} qwt.pro
        BUILD_COMMAND $(MAKE) VERBOSE=1
        INSTALL_COMMAND $(MAKE) install
        BUILD_IN_SOURCE 1
        DOWNLOAD_EXTRACT_TIMESTAMP FALSE
        DEPENDS
        LOG_DOWNLOAD 1
        LOG_UPDATE 1
        LOG_CONFIGURE 1
        LOG_BUILD 1
        LOG_TEST 1
        LOG_INSTALL 1 )
    SET( tpl_cmds build pre-configure configure done download download-impl mkdir 
        patch install build-test test check-test update post-install )
    SET( RM_LIST )
    FOREACH( tmp ${tpl_cmds} )
        SET( RM_LIST ${RM_LIST} QWT-${tmp} QWT-${tmp}-err.log QWT-${tmp}-out.log )
    ENDFOREACH()
    ADD_CUSTOM_TARGET( 
        QWT-clean
        ${CMAKE_COMMAND}         -E remove_directory ../QWT-build
        COMMAND ${CMAKE_COMMAND} -E make_directory   ../QWT-build
        COMMAND ${CMAKE_COMMAND} -E remove ${RM_LIST}
        COMMAND ${CMAKE_COMMAND} -E remove_directory "${CMAKE_INSTALL_PREFIX}/logs/QWT"
        COMMAND ${CMAKE_COMMAND} -E make_directory   "${CMAKE_INSTALL_PREFIX}/logs/QWT"
        COMMAND ${CMAKE_COMMAND} -E remove_directory QWT-prefix
        WORKING_DIRECTORY "${CMAKE_CURRENT_BINARY_DIR}/QWT-prefix/src/QWT-stamp" 
    )
ENDMACRO()

# Macro to configure GUI
MACRO( CONFIGURE_GUI )
    SET( TIMER_GUI_SOURCE_DIR "${${PROJ}_SOURCE_DIR}/gui" )
    SET( TIMER_GUI_INSTALL_DIR "${GUI_INSTALL_DIR}" )
    SET( TIMER_GUI_BUILD_DIR "${CMAKE_CURRENT_BINARY_DIR}/gui" )
    CONFIGURE_FILE( "${${PROJ}_SOURCE_DIR}/cmake/configure_GUI.cmake" "${TIMER_GUI_BUILD_DIR}/configure_GUI.cmake" @ONLY )
    INSTALL( SCRIPT "${TIMER_GUI_BUILD_DIR}/configure_GUI.cmake" )
ENDMACRO()

# Configure valgrind ( optional )
MACRO( CONFIGURE_VALGRIND )
    FIND_PACKAGE( Valgrind )
    IF ( Valgrind_INCLUDE_DIR )
        INCLUDE_DIRECTORIES( "${Valgrind_INCLUDE_DIR}" )
    ENDIF()
ENDMACRO()

# Configure CUDA
MACRO( CONFIGURE_CUDA )
    CHECK_ENABLE_FLAG( USE_CUDA FALSE )
    # Set CUDA standard ( always required in case down-stream packages enable CUDA )
    IF ( NOT DEFINED CMAKE_CUDA_STANDARD )
        IF ( CMAKE_CXX_STANDARD )
            SET( CMAKE_CUDA_STANDARD ${CMAKE_CXX_STANDARD} )
        ELSE()
            MESSAGE( FATAL_ERROR "Unable to set CMAKE_CUDA_STANDARD" )
        ENDIF()
    ENDIF()
    IF ( NOT CMAKE_CUDA_STANDARD EQUAL CMAKE_CXX_STANDARD )
        MESSAGE( WARNING "CMAKE_CUDA_STANDARD and CMAKE_CXX_STANDARD do not match, this may cause issues compiling some software" )
    ENDIF()
    # Find and configure CUDA
    IF ( USE_CUDA )
        MESSAGE( "Configuring CUDA" )
        ADD_DEFINITIONS( -DUSE_CUDA )
        IF ( ${CMAKE_VERSION} VERSION_LESS "3.17" )
            MESSAGE( FATAL_ERROR "We require CMake 3.17 or newer when compiling with CUDA" )
        ENDIF()
        SET( CMAKE_CUDA_HOST_COMPILER ${CMAKE_CXX_COMPILER} )
        ENABLE_LANGUAGE( CUDA )
        IF ( NOT DEFINED CUDA_HOME )
            GET_FILENAME_COMPONENT( CUDA_HOME "${CMAKE_CUDA_COMPILER}" DIRECTORY )
            GET_FILENAME_COMPONENT( CUDA_HOME "${CUDA_HOME}/.." REALPATH )
            MESSAGE( "   CUDA_HOME = ${CUDA_HOME}" )
        ENDIF()
        IF ( NOT DEFINED CUDA_ARCH_FLAGS )
            FOREACH( arch ${CMAKE_CUDA_ARCHITECTURES} )
                SET( CUDA_ARCH_FLAGS ${CUDA_ARCH_FLAGS} sm_${arch} )
            ENDFOREACH()
            SET( CUDA_ARCH_FLAGS "${CUDA_ARCH_FLAGS}" )
        ENDIF()
        SET( CMAKE_CUDA_STANDARD_REQUIRED ON )
        SET( CMAKE_CUDA_FLAGS "${CMAKE_CUDA_FLAGS} ${CUDA_FLAGS_EXTRA}" )
        IF ( USE_OPENMP )
            SET( CMAKE_CUDA_FLAGS "${CMAKE_CUDA_FLAGS} -Xcompiler -fopenmp" )
        ENDIF()
        IF ( USE_MPI )
            SET( MPI_CUDA_INCLUDE_DIRS ${MPI_CXX_INCLUDE_DIRS} )
            MESSAGE( "   MPI_CUDA_INCLUDE_DIRS=${MPI_CUDA_INCLUDE_DIRS}" )
            FOREACH( tmp ${MPI_CUDA_INCLUDE_DIRS} )
                SET( CMAKE_CUDA_FLAGS "${CMAKE_CUDA_FLAGS} -I${tmp}" )
            ENDFOREACH()
        ENDIF()
        MESSAGE( "   CMAKE_CUDA_FLAGS=${CMAKE_CUDA_FLAGS}" )
        MESSAGE( "   CUDA_FLAGS_EXTRA=${CUDA_FLAGS_EXTRA}" )
        MESSAGE( "   CMAKE_CUDA_HOST_COMPILER=${CMAKE_CUDA_HOST_COMPILER}" )
        # Set COMPILE_CXX_AS_CUDA
        IF ( NOT DEFINED COMPILE_CXX_AS_CUDA )
            SET( COMPILE_CXX_AS_CUDA FALSE )
        ENDIF()
        # Detect the number of GPUs available
        IF ( NOT DEFINED NUMBER_OF_GPUS )
            TRY_RUN( RUN_RESULT_VAR COMPILE_RESULT_VAR ${CMAKE_BINARY_DIR} ${CMAKE_CURRENT_SOURCE_DIR}/cmake/FindCudaGPUs.cu
                    CMAKE_FLAGS -DINCLUDE_DIRECTORIES:STRING=${CUDA_TOOLKIT_INCLUDE} -DLINK_LIBRARIES:STRING=${CUDA_CUDART_LIBRARY} COMPILE_OUTPUT_VARIABLE COMPILE_OUTPUT
                    RUN_OUTPUT_VARIABLE NUMBER_OF_GPUS )
            IF ( NOT NUMBER_OF_GPUS )
                MESSAGE( FATAL_ERROR "NUMBER_OF_GPUS was not set and not CUDA capable GPUs were detected:\n${COMPILE_OUTPUT}" )
            ENDIF()
            MATH( EXPR NUMBER_OF_GPUS ${NUMBER_OF_GPUS} )
            MESSAGE( "   Number of GPUs detected: ${NUMBER_OF_GPUS}" )
        ENDIF()
    ENDIF()
ENDMACRO()

# Configure HIP
MACRO( CONFIGURE_HIP )
    CHECK_ENABLE_FLAG( USE_HIP FALSE )
    # Set HIP standard ( always required in case down-stream packages enable HIP )
    IF ( NOT DEFINED CMAKE_HIP_STANDARD )
        IF ( CMAKE_CXX_STANDARD )
            SET( CMAKE_HIP_STANDARD ${CMAKE_CXX_STANDARD} )
        ELSE()
            MESSAGE( FATAL_ERROR "Unable to set CMAKE_HIP_STANDARD" )
        ENDIF()
    ENDIF()
    IF ( NOT CMAKE_HIP_STANDARD EQUAL CMAKE_CXX_STANDARD )
        MESSAGE( WARNING "CMAKE_HIP_STANDARD and CMAKE_CXX_STANDARD do not match, this may cause issues compiling some software" )
    ENDIF()
    # Find and configure HIP
    IF ( USE_HIP )
        MESSAGE( "Configuring HIP" )
        ADD_DEFINITIONS( -DUSE_HIP )
        IF ( ${CMAKE_VERSION} VERSION_LESS "3.21" )
            MESSAGE( FATAL_ERROR "We require CMake 3.21 or newer when compiling with HIP" )
        ENDIF()
        ENABLE_LANGUAGE( HIP )
        IF ( NOT DEFINED HIP_HOME )
            GET_FILENAME_COMPONENT( HIP_HOME "${CMAKE_HIP_COMPILER}" DIRECTORY )
            GET_FILENAME_COMPONENT( HIP_HOME "${HIP_HOME}/.." REALPATH )
            MESSAGE( "   HIP_HOME = ${HIP_HOME}" )
        ENDIF()
        IF ( NOT DEFINED HIP_ARCH_FLAGS )
            FOREACH( arch ${CMAKE_HIP_ARCHITECTURES} )
                SET( HIP_ARCH_FLAGS ${HIP_ARCH_FLAGS} sm_${arch} )
            ENDFOREACH()
            SET( HIP_ARCH_FLAGS "${HIP_ARCH_FLAGS}" )
        ENDIF()
        SET( CMAKE_HIP_STANDARD_REQUIRED ON )
        SET( CMAKE_HIP_FLAGS "${CMAKE_HIP_FLAGS} ${HIP_FLAGS_EXTRA}" )
        IF ( USE_OPENMP )
            SET( CMAKE_HIP_FLAGS "${CMAKE_HIP_FLAGS} -Xcompiler -fopenmp" )
        ENDIF()
        IF ( USE_MPI )
            SET( MPI_HIP_INCLUDE_DIRS ${MPI_CXX_INCLUDE_DIRS} )
            MESSAGE( "   MPI_HIP_INCLUDE_DIRS=${MPI_HIP_INCLUDE_DIRS}" )
            FOREACH( tmp ${MPI_HIP_INCLUDE_DIRS} )
                SET( CMAKE_HIP_FLAGS "${CMAKE_HIP_FLAGS} -I${tmp}" )
            ENDFOREACH()
        ENDIF()
        # Set COMPILE_CXX_AS_HIP
        IF ( NOT DEFINED COMPILE_CXX_AS_HIP )
            SET( COMPILE_CXX_AS_HIP FALSE )
        ENDIF()
        # Detect the number of GPUs available
        IF ( NOT DEFINED NUMBER_OF_GPUS )
            TRY_RUN(
                RUN_RESULT_VAR
                COMPILE_RESULT_VAR
                ${CMAKE_BINARY_DIR}
                ${CMAKE_CURRENT_SOURCE_DIR}/cmake/FindHIPGPUs.hip
                # CMAKE_FLAGS
                #     -DINCLUDE_DIRECTORIES:STRING=${HIP_TOOLKIT_INCLUDE}
                #     -DLINK_LIBRARIES:STRING=${HIP_HIPRT_LIBRARY}
                COMPILE_OUTPUT_VARIABLE COMPILE_OUTPUT
                RUN_OUTPUT_VARIABLE NUMBER_OF_GPUS )
            IF ( NOT NUMBER_OF_GPUS )
                MESSAGE( FATAL_ERROR "NUMBER_OF_GPUS was not set and no HIP capable GPUs were detected:\n${COMPILE_OUTPUT}" )
            ENDIF()
            MATH( EXPR NUMBER_OF_GPUS ${NUMBER_OF_GPUS} )
            MESSAGE( "   Number of GPUs detected: ${NUMBER_OF_GPUS}" )
        ENDIF()
    ENDIF()
    IF ( NOT USE_CUDA AND NOT USE_HIP )
        SET( NUMBER_OF_GPUS 0 )
    ENDIF()
ENDMACRO()
