FILE( READ "qwtconfig.pri" STR )
FILE( COPY_FILE "qwtconfig.pri" "qwtconfig.pri.orig" )
STRING( REPLACE "QWT_INSTALL_PREFIX = $$[QT_INSTALL_PREFIX]" "QWT_INSTALL_PREFIX    = $\${QWT_INSTALL_PREFIX}" STR "${STR}" )
STRING( REGEX REPLACE "unix {\n[ ] *QWT_INSTALL_PREFIX[^?]*QWT_INSTALL_DOCS" "QWT_INSTALL_DOCS" STR "${STR}" )
STRING( REPLACE "\nQWT_INSTALL_DOCS" "QWT_INSTALL_DOCS" STR "${STR}" )
STRING( REPLACE "\\" "" STR "${STR}" )
FILE( WRITE "qwtconfig.pri" "${STR}" )

